// Creator catalog — keep handles consistent with browse-data.js author initials.
window.CREATORS = [
  { id: "JR", name: "Jake Rivera",   handle: "@jakerivera",   role: "Automation lead",  bio: "Building no-code lead gen flows for B2B SaaS since 2019.",                          color: "#FF4D00", workflows: 18, installs: 4200, rating: 4.9, tier: "top",      joined: "2019", tools: ["HubSpot", "Gmail", "OpenAI"], topFlow: "Cold email reply detector + CRM router", location: "Austin, TX" },
  { id: "AL", name: "Aisha Lema",    handle: "@aishalema",    role: "AI specialist",    bio: "I turn GPT prompts into reliable production pipelines.",                            color: "#0066FF", workflows: 12, installs: 2800, rating: 4.7, tier: "top",      joined: "2022", tools: ["OpenAI", "Notion", "Buffer"], topFlow: "AI content repurposer for LinkedIn", location: "Lagos, NG" },
  { id: "MK", name: "Marcus Kim",    handle: "@marcuskim",    role: "Growth hacker",    bio: "Loves making boring finance automations until they print money.",                   color: "#7c3aed", workflows: 9,  installs: 1900, rating: 4.8, tier: "verified", joined: "2021", tools: ["Stripe", "Gmail", "Zapier"], topFlow: "Invoice overdue auto-chaser", location: "Berlin, DE" },
  { id: "TN", name: "Tara Novak",    handle: "@taranovak",    role: "SaaS operator",    bio: "Ex-founder. Now I build the ops automations I wish I'd had.",                       color: "#16a34a", workflows: 22, installs: 6100, rating: 4.9, tier: "top",      joined: "2020", tools: ["Stripe", "Slack", "Mixpanel"], topFlow: "Stripe failed-payment recovery", location: "Toronto, CA" },
  { id: "DS", name: "Dev Singh",     handle: "@devsingh",     role: "E-comm expert",    bio: "Shopify-first automations. Cart recovery is my whole personality.",                 color: "#FF4D00", workflows: 15, installs: 3400, rating: 4.6, tier: "verified", joined: "2021", tools: ["Shopify", "Twilio", "Bannerbear"], topFlow: "Abandoned cart recovery with AI copy", location: "Mumbai, IN" },
  { id: "PW", name: "Priya Walsh",   handle: "@priyawalsh",   role: "Finance ops",      bio: "Spreadsheets → APIs → automations. Numbers should report themselves.",              color: "#0066FF", workflows: 8,  installs: 1200, rating: 4.5, tier: "verified", joined: "2022", tools: ["QuickBooks", "Slack", "Airtable"], topFlow: "Weekly competitor price monitor", location: "Dublin, IE" },

  { id: "LC", name: "Leo Costa",     handle: "@leocosta",     role: "Sales engineer",   bio: "Pipeline plumbing for outbound teams. I make CRMs less awful.",                     color: "#db2777", workflows: 11, installs: 2100, rating: 4.7, tier: "verified", joined: "2021", tools: ["Salesforce", "Apollo", "Slack"], topFlow: "LinkedIn lead enrichment pipeline", location: "São Paulo, BR" },
  { id: "MC", name: "Maya Chen",     handle: "@mayachen",     role: "Marketing automation", bio: "Content workflows that survive contact with reality.",                          color: "#db2777", workflows: 14, installs: 2950, rating: 4.6, tier: "verified", joined: "2022", tools: ["Notion", "OpenAI", "Buffer"], topFlow: "Weekly Notion → blog post drafts", location: "Singapore" },
  { id: "OH", name: "Omar Hassan",   handle: "@omarhassan",   role: "Productivity coach", bio: "I help small teams stop forwarding emails to themselves.",                        color: "#0d9488", workflows: 6,  installs: 890,  rating: 4.4, tier: "verified", joined: "2023", tools: ["Notion", "Linear", "Slack"], topFlow: "AI meeting notes → action items", location: "Cairo, EG" },
  { id: "SR", name: "Sofia Reyes",   handle: "@sofiareyes",   role: "AI specialist",    bio: "RAG, embeddings, and pipelines that survive prod weirdness.",                        color: "#0066FF", workflows: 7,  installs: 1100, rating: 4.8, tier: "new",      joined: "2024", tools: ["OpenAI", "Pinecone", "Supabase"], topFlow: "AI-powered SEO content brief generator", location: "Madrid, ES" },
  { id: "NP", name: "Noah Park",     handle: "@noahpark",     role: "DevOps automation", bio: "GitHub Actions all the way down. CI/CD as a lifestyle.",                            color: "#1d4ed8", workflows: 10, installs: 1450, rating: 4.5, tier: "verified", joined: "2022", tools: ["GitHub", "Linear", "Slack"], topFlow: "Slack to Linear bug triage", location: "Seoul, KR" },
  { id: "ID", name: "Inès Dubois",   handle: "@inesdubois",   role: "Customer success", bio: "NPS, churn signals, and the workflows that actually act on them.",                  color: "#7c3aed", workflows: 5,  installs: 720,  rating: 4.6, tier: "new",      joined: "2024", tools: ["Typeform", "Stripe", "Slack"], topFlow: "Customer NPS auto-collector", location: "Paris, FR" },
  { id: "FW", name: "Felix Wagner",  handle: "@felixwagner",  role: "Data automation",  bio: "I love a good cron job. Daily digests are my love language.",                        color: "#16a34a", workflows: 13, installs: 2400, rating: 4.7, tier: "verified", joined: "2021", tools: ["Stripe", "BigQuery", "Gmail"], topFlow: "Daily revenue summary to email", location: "Vienna, AT" },
  { id: "AP", name: "Anya Petrov",   handle: "@anyapetrov",   role: "Marketing automation", bio: "Outreach, social proof, and the occasional vanity tweet.",                       color: "#db2777", workflows: 9,  installs: 1650, rating: 4.4, tier: "verified", joined: "2022", tools: ["Apify", "OpenAI", "Bannerbear"], topFlow: "Influencer DM outreach pipeline", location: "Prague, CZ" },
  { id: "KT", name: "Kai Tanaka",    handle: "@kaitanaka",    role: "Mobile automation", bio: "iOS Shortcuts power user gone pro. Phone-first automations.",                      color: "#FF4D00", workflows: 4,  installs: 540,  rating: 4.3, tier: "new",      joined: "2024", tools: ["Shortcuts", "Notion", "Airtable"], topFlow: "Job application tracker", location: "Tokyo, JP" },
  { id: "ZK", name: "Zara Khalid",   handle: "@zarakhalid",   role: "Finance ops",      bio: "Receipts → categorized expenses. I save founders 10 hours a month.",                color: "#b45309", workflows: 6,  installs: 980,  rating: 4.5, tier: "verified", joined: "2023", tools: ["QuickBooks", "Gmail", "OpenAI"], topFlow: "Expense receipt → QuickBooks", location: "Dubai, AE" },
];
